---
name: bludit
director_uuid: fb70f16a-4d6f-41f8-bc2e-0181a03dff18

releases:
- name: bludit
  version: latest

networks:
- name: default
  subnets:
  - range: 10.120.0.0/28
    reserved: [10.120.0.1]
    static: [10.120.0.2]
    cloud_properties:
      name: random

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

compilation:
  workers: 2
  network: default
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
  - name: bludit
    templates:
    - name: bludit
    instances: 1
    resource_pool: default
    networks:
    - name: default
    properties: {}
